#spring:
#  datasource:
#    url: jdbc:h2:mem:test #메모리 안(jvm)에서 테스트 가능
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database: h2
#    hibernate:
#      ddl-auto: create  #기본 create-drop으로 작동
#    properties:
#      hibernate:
##        show_sql: true
#        format_sql: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/animalhood
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: hyun0712*
  jpa:
#    open-in-view: false
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 191482185001-rrhs18htqikock2r3nbic13cc6pvb2fl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

imgLocation: /Users/hyun/Desktop/image/

uploadPath: file:///Users/hyun/Desktop/image/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
 #   org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer: ERROR

jwt:
  issuer: cauduetsch@gmail.com
  secret_key: study-springboot
